core/urls.py
from django.urls import path
from .views import (
    About,
    Contact,
    Cart,
    user_login,
    signup,
    ItemDetailView,
    CheckoutView,
    HomeView,
    OrderSummaryView,
    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart,
    # PaymentView,
    AddCouponView,
    RequestRefundView,

    initiate_payment,
    payment_callback,

    verify_payment
)

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('about/', About, name='about'),
    path('contact/', Contact, name='contact'),
    path('login/',user_login, name='login'),
    path('signup/', signup, name='signup'),
    
    path('cart/', Cart, name='cart'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),

    # path('product/<int:pk>/', ItemDetailView.as_view(), name='item_detail'),

    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart, name='remove-single-item-from-cart'),
    # path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund'),

    path('initiate_payment/', initiate_payment, name='initiate_payment'),
    path('payment_callback/', payment_callback, name='payment_callback'),
    
    path('verify-payment/<str:ref>', verify_payment, name='verify-payment')
]

nessa_skin_goal/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core'))
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

core/forms.py
from django import forms
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
import re

# from .fields import NigerianStateField
from phonenumber_field.formfields import PhoneNumberField


PAYMENT_CHOICES = (
    ('PS', 'paystack'),
    ('P', 'PayPal')
)





class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.',
     widget=forms.EmailInput(attrs={'placeholder': 'Email'}))

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['placeholder'] = 'Username'
        self.fields['password1'].widget.attrs['placeholder'] = 'Password'
        self.fields['password2'].widget.attrs['placeholder'] = 'Confirm Password'

     # Remove default help text for password fields
        self.fields['email'].help_text = ''
        self.fields['username'].help_text = ''
        self.fields['password1'].help_text = ''
        self.fields['password2'].help_text = ''

    def clean_password1(self):
        password1 = self.cleaned_data.get('password1')
        
        # Perform custom password validation
        if len(password1) < 8:
            raise forms.ValidationError("Your password must contain at least 8 characters.")
        if password1.isdigit():
            raise forms.ValidationError("Your password can’t be entirely numeric.")
        return password1

    def clean_password2(self):
        password2 = self.cleaned_data.get('password2')
        password1 = self.cleaned_data.get('password1')

        # Check if passwords match
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("The two password fields didn't match.")
        return password2


    def clean_username(self):
        username = self.cleaned_data.get('username')
        # Add custom username validation here if needed
        if not re.match(r'^\w+$', username):
            raise forms.ValidationError("Username can only contain letters, digits, and underscores.")

        return username

    def clean_email(self):
        email = self.cleaned_data.get('email')
        # Add custom email validation here if needed
        if not re.match(r'^[\w\.-]+@[a-zA-Z0-9-]+\.[a-zA-Z]{2,}$', email):
            raise forms.ValidationError("Enter a valid email address.")
        return email

class LoginForm(forms.Form):
    username = forms.CharField(max_length=150, widget=forms.TextInput(attrs={'class': 'input-field','placeholder': 'Username'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'input-field','placeholder': 'Password'}))






# class CheckoutForm(forms.Form):
#     shipping_address = forms.CharField(required=False)
#     shipping_address2 = forms.CharField(required=False)
#     shipping_country = CountryField(blank_label='(select country)').formfield(
#         required=False,
#         widget=CountrySelectWidget(attrs={
#             'class': 'custom-select d-block w-100',
#         }))
#     shipping_zip = forms.CharField(required=False)

#     billing_address = forms.CharField(required=False)
#     billing_address2 = forms.CharField(required=False)
#     billing_country = CountryField(blank_label='(select country)').formfield(
#         required=False,
#         widget=CountrySelectWidget(attrs={
#             'class': 'custom-select d-block w-100',
#         }))
#     billing_zip = forms.CharField(required=False)

#     same_billing_address = forms.BooleanField(required=False)
#     set_default_shipping = forms.BooleanField(required=False)
#     use_default_shipping = forms.BooleanField(required=False)
#     set_default_billing = forms.BooleanField(required=False)
#     use_default_billing = forms.BooleanField(required=False)

#     payment_option = forms.ChoiceField(widget=forms.RadioSelect, choices=PAYMENT_CHOICES)


class CheckoutForm(forms.Form):
    delivery_address = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'No 23 Main Street'
    }))
    country = CountryField(blank_label='(select country)').formfield(
        widget=CountrySelectWidget(attrs={
            'class': 'country-form'
    }))
    # state = NigerianStateField()

    phone_number = PhoneNumberField()

    save_info = forms.BooleanField(widget=forms.CheckboxInput())
    payment_option = forms.ChoiceField(widget=forms.RadioSelect, choices=PAYMENT_CHOICES)









class CouponForm(forms.Form):
    code = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'coupon-input',
        'placeholder': 'Promo code',
        'aria-label': 'Recipient\'s username',
        'aria-describedby': 'basic-addon2'
    }))


class RefundForm(forms.Form):
    ref_code = forms.CharField()
    message = forms.CharField(widget=forms.Textarea(attrs={
        'rows': 4
    }))
    email = forms.EmailField()


class PaymentForm(forms.Form):
    stripeToken = forms.CharField(required=False)
    save = forms.BooleanField(required=False)
    use_default = forms.BooleanField(required=False)

core/views.py
import random
import string

import stripe
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import redirect, render, get_object_or_404
from django.utils import timezone
from django.views.generic import ListView, DetailView, View

from .forms import CheckoutForm, CouponForm, RefundForm, PaymentForm, SignUpForm, LoginForm
from .models import Item, OrderItem, Order, Payment, Coupon, Refund, UserProfile

from django.contrib.auth import login, authenticate

from django.http import JsonResponse
from paystackapi.paystack import Paystack





def About(request):
    return render(request, 'about.html')

def Contact(request):
    return render(request, 'contact.html')

def Cart(request):
    return render(request, 'cart.html')



def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('core:login')
    else:
        form = SignUpForm()
    return render(request, 'signup.html', {'form': form})

def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                # Redirect to the page the user originally intended to access
                next_url = request.GET.get('next')
                if next_url:
                    return redirect(next_url)
                else:
                    return redirect('/')  # Redirect to home page after successful login
            else:
                # Authentication failed
                form.add_error(None, 'Invalid username or password')
    else:
        form = LoginForm()
    return render(request, 'login.html', {'form': form})





def create_ref_code():
    return ''.join(random.choices(string.ascii_lowercase + string.digits, k=20))


def products(request):
    context = {
        'items': Item.objects.all()
    }
    return render(request, "products.html", context)


def is_valid_form(values):
    valid = True
    for field in values:
        if field == '':
            valid = False
    return valid


class CheckoutView(View):
    def get(self, request, *args, **kwargs):
        form = CheckoutForm()
        context = {
            'form': form
            }
        return render(self.request, "checkout.html", context)

    def post(self, request, *args, **kwargs):
        form = CheckoutForm(self.request.POST or None)
        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
            if form.is_valid():
                print("Form is valid. Data:", form.cleaned_data)  # Print cleaned data for debugging
                
                street_address = form.cleaned_data.get('street_address')
                apartment_address = form.cleaned_data.get('apartment_address')
                country = form.cleaned_data.get('country')
                zip = form.cleaned_data.get('zip')
                # TODO: add functionality to these fields
                # same_shipping_address = form.cleaned_data.get('same_shipping_address')
                # save_info = form.cleaned_data.get('save_info')
                Payment_option = form.cleaned_data.get('Payment_option')
                billing_address = BillingAddress(
                    user = self.request.user,
                    street_address = street_address,
                    apartment_address = apartment_address,
                    country = country,
                    zip = zip
                )
                billing_address.save()
                order.billing_address = billing_address
                order.save()

                print("Form data received:") 
                print(self.request.POST)

                if Payment_option == 'PS':
                    return redirect('core:initiate_payment', Payment_option='paystack')
                elif Payment_option == 'P':
                    return redirect('core:payment', Payment_option='Paypal')
                else:
                    messages.warning(self.request, "invalid payment option selected")
                    return redirect('core:checkout')

        except ObjectDoesNotExist:
            messages.warning(self.request, "You do not have an active order")
            return redirect("core:order-summary")

      







def place_order(request):
    if request.method == 'POST':
        form = CheckoutForm(request.POST)
        if form.is_valid():
            var = form.save(commit=False)
            product = Item.objects.get(pk=1)
            var.product = product
            var.user = request.user
            var.total_cost = product.price * var.item_amount
            # var.total_cost = product.price * var.order_item.quantity
            var.save()
            payment = Payment.objects.create(amount=var.total_cost, email=request.user.email, user=request.user)
            payment.save()
            pk = settings.PAYSTACK_PUBLIC_KEY
            context = {
                'total_cost':var.total_cost,
                'item_amount':var.item_amount,
                'payment':payment,
                'paystack_pub_key':pk,
                'amount_value':payment.amount_value()
            }
            request.session['order_id'] = var.id
            return render(request, 'make_payment.html', context)
        else:
            messages.warning(request, 'Error, Something went wrong')
            return redirect('place-order')
    else:
        form = CheckoutForm()
        context = {'form':form}
        return render(request, 'place_order.html', context)





















def verify_payment(self, request, ref):
    payment = Payment.objects.get(ref=ref)
    verified = payment.verify_payment()

    if verified:
        pk = request.session['order_id']
        order = Order.objects.get(pk=pk)
        order.is_verified = True
        order.save()
        context = {'placed_order': pk, 'payment':payment}
        return render(request, 'success.html', context)
    else:
        messages.warning(request, 'sorry your order was not processed. please contact Nessa support.')
        return redirect('/')


















































class HomeView(ListView):
    model = Item
    paginate_by = 10
    template_name = "home.html"



def initiate_payment(request):
    if request.method == 'POST':
        amount = request.POST.get('amount')  # Assuming you have a form field for amount
        paystack_secret_key = settings.PAYSTACK_SECRET_KEY
        paystackapi = Paystack.Transaction(paystack_secret_key)

        response = paystackapi.initialize(amount=amount, email=request.user.email)  # Assuming you have a user object

        return JsonResponse(response)

    return render(request, 'make_payment.html')




def payment_callback(request):
    if request.method == 'POST':
        paystack_secret_key = settings.PAYSTACK_SECRET_KEY
        paystackapi = Paystack.Transaction(paystack_secret_key)

        # Verify the payment
        response = paystackapi.verify(request.body.decode('utf-8'))

        # Process the payment status
        if response.get('status'):
            payment_status = response.get('data').get('status')

            if payment_status == 'success':
                # Payment successful, process the order or do something else
                return JsonResponse({'status': 'success'})

    # Payment failed or invalid callback, handle accordingly
    return JsonResponse({'status': 'error'})








class OrderSummaryView(LoginRequiredMixin, View):
    def get(self, *args, **kwargs):
        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
            context = {
                'object': order
            }
            return render(self.request, 'order_summary.html', context)
        except ObjectDoesNotExist:
            messages.warning(self.request, "You do not have an active order")
            return redirect("/")
        
        

class ItemDetailView(DetailView):
    model = Item
    template_name = "product.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Retrieve the current item
        current_item = context['object']
        # Get related items with the same category
        related_items = Item.objects.filter(category=current_item.category).exclude(id=current_item.id)[0:2]
        context['related_items'] = related_items
        return context




@login_required
def add_to_cart(request, slug):
    item = get_object_or_404(Item, slug=slug)
    
    # Get the user's active order or create a new one if none exists
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs.first()
    else:
        ordered_date = timezone.now()
        order = Order.objects.create(
            user=request.user, 
            ordered_date=ordered_date
        )

    # Check if the item already exists in the order
    order_item, created = OrderItem.objects.get_or_create(
        order=order,
        item=item,
        ordered=False
    )

    # If the item already exists, update its quantity; otherwise, add it to the order
    if not created:
        order_item.quantity += 1
        order_item.save()
        messages.info(request, "This item quantity was updated.")
    else:
        messages.info(request, "This item was added to your cart.")

    return redirect("core:order-summary")




@login_required
def remove_from_cart(request, slug):
    item = get_object_or_404(Item, slug=slug)

core/templates/about.html
{% extends 'base.html' %}

{% load static %}



{% block content %}
<body>
    
    <section id="page-header" class="about-header">
        <h2>#Know Us</h2>
        <p>KNOW US Lorem ipsum dolor sit amet consectetu</p>
        <a href="#" class="to-top">
            <i class="fas fa-chevron-up"></i>
        </a>
    </section>
  
    <section id="about-head" class="section-p1">
        <img src="{% static 'images/img4.png' %}" alt="" style="height: 500px;" class="about-image">
        <div>
            <h2 class="about-h2">Who we are</h2>
            <p class="about-p">Welcome to Nessa Skin Goal, where beauty meets science and expertise blends seamlessly with 
                care. We are not just a skincare brand; we are your trusted partners on the journey to healthier,
                 radiant skin. At Nessa Skin Goal, we understand that each skin is unique and deserves personalized
                  attention. With years of experience and a passion for skincare, we have crafted a range of products
             that cater to all your skin concerns, from acne to eczema, from pigmentation to black spots.</p>
            
             <p class="about-p">
                Our team comprises dedicated skincare specialists, researchers, and beauty enthusiasts, all driven by
                 a common goal: to empower individuals to feel confident in their skin. We believe
                 that skincare is not just about superficial beauty but also about nurturing and
                  restoring your skin's natural health and vitality.
             </p>
             <br>
            
            <a href="" class="shop-btn">Shop Now</a>

            <br><br><br>

            <marquee bgcolor="#ccc" loop="-5"  scrollamount="10" width="100%"> Enjoy Up to 70% Off - All Products & Accessories</marquee>
        </div>
    </section>

    
    <section id="about-head" class="section-p1">
        <div>
            <h2 class="about-h2">Our Mission</h2>
            <p class="about-p">Our mission at Nessa Skin Goal is simple yet profound: to provide effective skincare 
                solutions that repair, restore, and maintain healthy skin for everyone. We strive to harness the latest
                 advancements in skincare science while remaining true to our commitment to using safe, natural ingredients.
                  Through our products and expertise, 
                we aim to educate and empower individuals to embrace their unique skin journey with confidence and grace.
            </p>
            
            <br>
        </div>
        <img src="{% static 'images/img5.png' %}" alt="" style="height: 500px; margin-left: 50px; " class="about-image">
    </section>

    <section id="about-head" class="section-p1">
        <img src="{% static 'images/img6.png' %}" alt="" style="height: 500px;" class="about-image">
        <div>
            <h2 class="about-h2">Our Vision</h2>
            <p class="about-p">At Nessa Skin Goal, we envision a world where skincare is not just a routine but a transformative experience—a 
                journey of self-discovery and self-care. We aspire to be the guiding light for those navigating the complexities of 
                skincare, offering not just products but also knowledge, support, and inspiration. Our vision is to redefine beauty 
                standards by promoting skin health and self-love, one radiant complexion at a time.
            </p>

            <p>Join us on this exhilarating quest for healthier, happier skin. Together, let's unlock the true potential of your skin
                 and embark on a journey towards your ultimate skin goals.</p>
            
            <br>
        </div>
        
    </section>


    
    <!-- <section id="about-app" class="section-padding">
        <h2>Download Our <a href="#">app</a> </h2>
        <div class="video">
            <video autoplay muted loop src="img/about/1.mp4"></video>
        </div>
    </section> -->

    <section id="feature" class="section-p1">
        <div class="fe-box">
            <img src="{% static 'images/features' %}/f1.png" alt="">
            <h6>Lorem ipsum</h6>
        </div>
        <div class="fe-box">
            <img src="{% static 'images/features' %}/f2.png" alt="">
            <h6>Lorem, ipsum.</h6>
        </div>
        <div class="fe-box">
            <img src="{% static 'images/features' %}/f3.png" alt="">
            <h6>Lorem, ipsum.</h6>
        </div>
        <div class="fe-box">
            <img src="{% static 'images/features' %}/f4.png" alt="">
            <h6>Lorem, ipsum.</h6>
        </div>
        <div class="fe-box">
            <img src="{% static 'images/features' %}/f5.png" alt="">
            <h6>Lorem, ipsum.</h6>
        </div>
        <div class="fe-box">
            <img src="{% static 'images/features' %}/f6.png" alt="">
            <h6>Lorem, ipsum.</h6>
        </div>
    </section>



    <section >
        <div>

            <h2 class="">Frequently Asked Questions</h2>
   
            <div class="accordion">
            <div class="accordion-item">
                <div class="accordion-header">Is skin care Unisex?</div>
                <div class="accordion-content">
                <p>Skin care is gender neutral, everyone deserves abeautiful and healthy skin.</p>
                </div>
            </div>
            <div class="accordion-item">
                <div class="accordion-header">Is Sun screen compulsory?</div>
                <div class="accordion-content">
                <p>Yes, wearing Sunscreen on a daily basis is essential as it protects your skin from sun sensitivity that might cause a skin damage.</p>
                </div>
            </div>
            <div class="accordion-item">
                <div class="accordion-header">What happens when I stop using skincare products?</div>
                <div class="accordion-content">
                <p>Your skin will likely return to its natural state or what is often referred to as it's "baseline" condition.</p>
                </div>
            </div>
            </div>
            
    <script>
      document.addEventListener('DOMContentLoaded', function() {
        const accordionItems = document.querySelectorAll('.accordion-item');
    
        accordionItems.forEach(item => {
          const header = item.querySelector('.accordion-header');
          header.addEventListener('click', function() {
            item.classList.toggle('active');
          });
        });
      });
    </script>
    
        </div>
        
    </section>

    
{% endblock %}

core/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %} | Nessa Skin Goal</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" />


    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/fontawesome.min.css' %}">
    
    <script src="{% static 'js/fontawesome.min.js' %}"></script>
    <!-- <script src="fontawesomefree/js/all.min.js"></script> -->

    <style>
        .error-message {
            color: red;
        }
    </style>
</head>
<body>
    
    <section id="header">
        <a href="#"><img src="{% static 'images/logo.png' %}" class="logo" alt=""></a>

        <div>
            <ul id="navbar">
                <a href="#" id="close"><i class='fa fa-close'></i></a>
                <li><a class="active" href="{% url 'core:home' %}">Home</a></li>
                <li><a href="#">Shop</a></li>
                <li><a href="{% url 'core:cart' %}">Cart</a></li>    
                
                <i class="fas fa-home"></i>

                <li><a href="{% url 'core:about' %}">About</a></li>
                <li><a href="{% url 'core:contact' %}">Contact</a></li>
                <li id="lg-bag"><a href="cart"><i class="fa fa-shopping-bag" aria-hidden="true"></i></a></li>
            </ul>
        </div>
        <div id="mobile">
            <a href="cart"><i class="fa fa-shopping-bag" aria-hidden="true"></i></a>
            <i id="bar" class="fa fa-bars" aria-hidden="true"></i>      
                 
        </div>
    </section>

    {% block content %}

    {% endblock %}



    <footer class="section-p1">
        <div class="col">
            <img class="logo" src="{% static 'images/logo.png' %}" alt="">
            <h4>Contact</h4>
            <p class="address"><strong>Address :</strong> Ozomagala by leventis Junction,
                Opposite Susu School Onitsha, Anambra State.</p>
            <p><strong>Phone :</strong> 08130663364</p>
            <p><strong>Hours :</strong> 8am to 6pm</p>
            <div class="follow">
                <h4>Follow Us</h4>
                <div class="icon">
                    <i class="fab fa-facebook-f"></i>
                    <i class="fab fa-twitter"></i>
                    <i class="fab fa-instagram"></i>
                    <i class="fab fa-pinterest-p"></i>
                    <i class="fab fa-youtube"></i>
                </div>
            </div>
        </div>
    
        <div class="col">
            <h4>About</h4>
            <a href="about.html">About US</a>
            <a href="#">Delivery Information</a>
            <a href="#">Privacy Policy</a>
            <a href="#">Terms & Conditions</a>
            <a href="contact.html">Contact Us</a>
        </div>
    
        <div class="col">
            <h4>MY Account</h4>
            <a href="#">Sign In</a>
            <a href="cart.html">View Cart</a>
            <a href="#">My Wishlist</a>
            <a href="#">Track My Order</a>
            <a href="#">Help</a>
        </div>
    
    
        <div class="col install">
            <h4>Install App</h4>
            <p>From app store or Google PLay Store</p>
            <div class="row">
                <img src="{% static 'images/pay/app.jpg' %}" alt="">
                <img src="{% static 'images/pay/play.jpg' %}" alt="">
            </div>
            <p>Secured payment Gateways</p>
            <img src="{% static 'images/pay/pay.png' %}" alt="">
        </div>
    
        <div class="copyright">
            <p>&copy Nessa Skin Goal, All Rights Reserved.</p>
        </div>
    
       </footer>
    
        <script src="{% static 'script.js' %}"></script>
</body>
</html>

core/templates/login.html
{% extends 'base.html' %}

{% load static %}



{% block content %}
<body>

<div class="wrapper">
	<div class="header">
		<div class="top">

			<h4>Login</h4>
			<form method="post">
				{% csrf_token %}
				{{ form.as_p }}
				<button class="submit-btn" type="submit">Login</button>
			</form>

			
			<div class="dif">
				<div class="forgot">
					<a href="#">Forgot password?</a>
				</div>
			</div>
		</div>
		<div class="signup">
			<p>Don't have an account? <a href="signup">Sign up</a></p>
		</div>

	

	</div>

</div>

</body>

{% endblock %}

core/templates/make_payment.html
{% extends "base.html" %}

{% block content %}

<div>
    <h2>Hello You are about to pay for {{item_amount}} Products and the total cost is NGN{{total_cost}}</h2>
</div>
<button onclick="payWithPaystack()" class="payment-btn">Proceed to Payment</button>


<script>
    function payWithPaystack() {
        let currency = 'NGN';
        let plan = '';
        let ref = '{{payment.ref}}'
        let amount = '{{payment.amount}}';
        let obj = {
            key: '{{paystack_pub_key}}',
            email: '{{payment.email}}',
            amount: '{{amount_value}}',
            ref:ref,
            callback: function (response) {
                windows.location.href = "{% url 'verify_payment' payment.ref %}";
            },
        };
        if (Boolean(currency)) {
            obj.currency = currency.toLocaleUpperCase();
        }
        if (Boolean(plan)) {
            obj.plan = plan;
        }
        var handler = PaystackPop.setup(obj);
        handler.openIframe();
    }
</script>


<script src="https://js.paystack.co/v1/inline.js"></script>

{% endblock %}

core/templates/order_snippet.html
<div class="">
    <h4 class="order-snippet-header">
    <span class="order-title">Your cart</span>
    <span class="order-count">{{ order.order_items.count }}</span>
    </h4>
    <ul class="your-cart">
        {% for order_item in order.order_items.all %}
        <li class="your-cart-li">
            <div>
            <h6 class="">{{ order_item.quantity }} x {{ order_item.item.title}}</h6>
            <small class="order-description">{{ order_item.item.description}}</small>
            </div>
            <span class="order-price">&#x20a6; {{ order_item.get_final_price }}</span>

        </li>
        {% endfor %}

        {% if order.coupon %}
        <li class="your-cart-li">
            <div class="">
            <h6 class="">Promo code</h6>
            <small>{{ order.coupon.code }}</small>
            </div>
            <span class="">-&#x20a6; {{ order.coupon.amount }}</span>
        </li>
        {% endif %}
        <li class="your-cart-li br">
            <span>Total (USD)</span>
            <strong>&#x20a6; {{ order.get_total }}</strong>
        </li>
    </ul>

    {% if DISPLAY_COUPON_FORM %}
    <form class="coupon-form" action="{% url 'core:add-coupon' %}" method="POST">
        {% csrf_token %}
        <div class="input-group">
            {{ couponform.code }}
            <div class="input-group-append">
            <button class="Redeem-btn" type="submit">Redeem</button>
            </div>
        </div>
    </form>
    {% endif %}

</div>